language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

before_script: 
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  - rustup component add rustfmt
  - if [ $TRAVIS_RUST_VERSION != 'nightly' ]; then rustup component add clippy; else rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy; fi


script:
  - cargo fmt --all -- --check
  - cargo clippy --all-features --all-targets -- -D warnings
  - cargo test --verbose --all-features --all-targets
  - cargo build --verbose --all-features --all-targets

matrix:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true
