language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

before_script:
  - rustup component add rustfmt clippy

script:
  - cargo fmt --all -- --check
  - cargo clippy --all-features -- -D warnings
  - cargo test --verbose --all --all-features
  - cargo build --verbose --all --all-features

cache: cargo

matrix:
  allow_failures:
    - rust: nightly