language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

before_script:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  - rustup component add rustfmt clippy

script:
  - cargo fmt --all -- --check
  - cargo clippy --all-features --all-targets -- -D warnings
  - cargo test --verbose --all-features --all-targets
  - cargo build --verbose --all-features --all-targets

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
