[package]
name = "libunftp"
version = "0.12.0"
authors = [
    "Agoston Horvath <ahorvath@bol.com>",
    "Dávid Kosztka <dkosztka@bol.com>",
    "Hannes de Jager <hdejager@bol.com>",
    "Koen Wilde <koen@chillheid.nl>",
    "Maarten Dirkse <mdirkse@bol.com>",
    "Steven Meunier <smeunier@bol.com>",
    "Rob klein Gunnewiek <rkleingunnewiek@bol.com>",
   ]
description = "Extensible, async, cloud orientated FTP(S) server library."
documentation = "https://docs.rs/libunftp/"
repository = "https://github.com/bolcom/libunftp"
license = "Apache-2.0"
readme = "README.md"
keywords = ["ftp", "ftps"]
categories = ["network-programming"]
edition = "2018"

[dependencies]
async-trait = "0.1.40"
regex = "1.3.9"
futures = {version = "0.3.5", features = ["std"]}
tokio = { version = "0.2.22", features = ["rt-core", "net", "sync", "io-util", "macros", "time", "fs"]}
tokio-util = { version = "0.3.1", features=["codec", "compat"] }
tokio-rustls = { version = "0.14.1" }
rustls = "0.18.1"
bytes = "0.5.6"
lazy_static = "1.4.0"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_info"] }
slog-stdlog = "4.0.0"
chrono = {version = "0.4.15", features = ["serde"]}
failure = "0.1.8"
failure_derive = "0.1.8"
derive_more = "0.99.9"
thiserror = "1.0.20"
hyper = { version = "0.13.7", optional = true, features= ["runtime", "stream"]}
percent-encoding = { version = "2.1.0", optional = true }
serde = { version = "1.0.115", optional = true, features = ["derive"] }
serde_json = { version = "1.0.56", optional = true }
path_abs = "0.5.0"
prometheus = "0.10.0"
uuid = { version = "0.8.1", features = ["v4"] }
rand = "0.7.3"
tracing-futures = { version = "0.2.4", features = ["std", "std-future", "futures-03"]}
tracing-attributes = "0.1.11"
tracing = "0.1.19"

hyper-rustls = {version = "0.21.0", optional = true}
yup-oauth2 = {version = "4.1.2", optional = true}
mime = {version = "0.3.16", optional = true}
itertools = "0.9.0"
proxy-protocol = {version = "0.1.1"}

[target.'cfg(unix)'.dependencies]
pam-auth = { package = "pam", version = "0.7.0", optional = true }

[dev-dependencies]
tempfile = "3.1.0"
async_ftp = "4.0.1"
pretty_env_logger = "0.4.0"
pretty_assertions = "0.6.1"
tokio = { version = "0.2.22", features = ["rt-threaded"]}
clap = "2.33.3"
tracing-subscriber = "0.2.11"
log = "0.4.11"

[features]
pam_auth = ["pam-auth"]
rest_auth = ["hyper", "percent-encoding", "serde", "serde_json"]
jsonfile_auth = ["serde", "serde_json"]
cloud_storage = ["oauth2", "mime", "percent-encoding", "hyper", "serde", "serde_json"]
oauth2 = ["yup-oauth2", "hyper-rustls"]

[[example]]
name = "gcs"
required-features = ["cloud_storage"]

[[example]]
name = "rest"
required-features = ["rest_auth"]

[[example]]
name = "jsonfile_auth"
required-features = ["jsonfile_auth"]
