[package]
name = "libunftp"
version = "0.16.2"
authors = [
    "Agoston Horvath <ahorvath@bol.com>",
    "Dávid Kosztka <dkosztka@bol.com>",
    "Hannes de Jager <hdejager@bol.com>",
    "Koen Wilde <koen@chillheid.nl>",
    "Maarten Dirkse <mdirkse@bol.com>",
    "Steven Meunier <smeunier@bol.com>",
    "Rob klein Gunnewiek <rkleingunnewiek@bol.com>",
   ]
description = "Extensible, async, cloud orientated FTP(S) server library."
documentation = "https://docs.rs/libunftp/"
repository = "https://github.com/bolcom/libunftp"
license = "Apache-2.0"
readme = "README.md"
keywords = ["ftp", "ftps"]
categories = ["network-programming"]
edition = "2018"

[workspace]

members = [
    "crates/unftp-sbe-gcs",
    "crates/unftp-auth-rest",
    "crates/unftp-auth-jsonfile"
]

[dependencies]
async-trait = "0.1.42"
bytes = "1.0.1"
chrono = {version = "0.4.19", features = ["serde"]}
derive_more = { version = "0.99.11", features = ["display"] }
futures = {version = "0.3.12", features = ["std"]}
itertools = "0.10.0"
lazy_static = "1.4.0"
mime = {version = "0.3.16", optional = true}
path_abs = "0.5.0"
prometheus = "0.11.0"
proxy-protocol = "0.2.0"
rand = "0.8.3"
rustls = "0.19.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_info"] }
slog-stdlog = "4.1.0"
thiserror = "1.0.23"
tokio = { version = "1.2.0", features = ["rt", "net", "sync", "io-util", "macros", "time", "fs"]}
tokio-stream = "0.1.3"
tokio-rustls = { version = "0.22.0" }
tokio-util = { version = "0.6.3", features=["codec", "compat"] }
tracing = "0.1.23"
tracing-attributes = "0.1.12"
tracing-futures = { version = "0.2.4", features = ["std", "std-future", "futures-03"]}
uuid = { version = "0.8.2", features = ["v4"] }

[target.'cfg(unix)'.dependencies]
pam-auth = { package = "pam", version = "0.7.0", optional = true }

[dev-dependencies]
async_ftp = "5.0.0"
clap = "2.33.3"
slog-term = "2.8.0"
slog-async = "2.6.0"
pretty_assertions = "0.6.1"
tempfile = "3.2.0"
tokio = { version = "1.2.0", features = ["rt-multi-thread"]}
tracing-subscriber = "0.2.15"
more-asserts = "0.2.1"
unftp-sbe-gcs = { path = "../libunftp/crates/unftp-sbe-gcs"}
unftp-auth-rest = { path = "../libunftp/crates/unftp-auth-rest"}
pretty_env_logger = "0.4.0"

[features]
pam_auth = ["pam-auth"]

[profile.release]
lto = "fat"
codegen-units = 1

[package.metadata.docs.rs]
all-features = true

