[package]
name = "unftp-auth-jsonfile"
version = "0.1.1"
description = "An authenticator back-end for libunftp that authenticates against a JSON file"
authors = [
    "Agoston Horvath <ahorvath@bol.com>",
    "Dávid Kosztka <dkosztka@bol.com>",
    "Hannes de Jager <hdejager@bol.com>",
    "Rob klein Gunnewiek <rkleingunnewiek@bol.com>",
]
edition = "2018"
license = "Apache-2.0"
keywords = ["libunftp", "unftp", "ftp", "ftps", "json"]
categories = ["network-programming"]
documentation = "https://docs.rs/unftp-auth-jsonfile"
homepage = "https://github.com/bolcom/libunftp/tree/master/crates/unftp-auth-jsonfile"
repository = "https://github.com/bolcom/libunftp/tree/master/crates/unftp-auth-jsonfile"
readme = "README.md"

[dependencies]
async-trait = "0.1.50"
libunftp = { version="0.17.4", path="../../"}
unftp-sbe-fs = { version="0.1", path="../unftp-sbe-fs"}
serde = { version = "1.0.125", features = ["derive"] }
serde_json = { version = "1.0.64" }
tokio = { version = "1.5.0", features = ["rt", "time"]}
tracing = "0.1.25"
tracing-attributes = "0.1.15"
ring = "0.16.20"
base64 = "0.13.0"
bytes = "1.0.1"
valid = "0.3.1"
iprange = "0.6.4"
ipnet = "2.3.0"

[dev-dependencies]
pretty_env_logger = "0.4.0"
