[package]
name = "unftp-sbe-gcs"
version = "0.1.0"
authors = ["Hannes de Jager <hdejager@bol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.2.0", features = ["rt", "net", "sync", "io-util", "macros", "time", "fs"]}
tokio-stream = "0.1.3"
tokio-util = { version = "0.6.3", features=["codec", "compat"] }
async-trait = "0.1.42"
futures = {version = "0.3.12", features = ["std"]}
tracing = "0.1.23"
tracing-attributes = "0.1.12"
tracing-futures = { version = "0.2.4", features = ["std", "std-future", "futures-03"]}
hyper = { version = "0.14.4", features= ["client", "runtime", "stream", "http1"]}
serde = { version = "1.0.123", features = ["derive"] }
serde_json = { version = "1.0.62"}
yup-oauth2 = {version = "5.0.3"}
chrono = {version = "0.4.19", features = ["serde"]}
hyper-rustls = { version = "0.22.1"}
percent-encoding = { version = "2.1.0"}
bytes = "1.0.1"
mime = {version = "0.3.16"}

[dependencies.libunftp]
path="../../"
version="0.16.2"

[dev-dependencies]
async_ftp = "5.0.0"
clap = "2.33.3"
slog-term = "2.8.0"
slog-async = "2.6.0"
pretty_assertions = "0.6.1"
pretty_env_logger = "0.4.0"
tempfile = "3.2.0"
tokio = { version = "1.2.0", features = ["rt-multi-thread"]}
tracing-subscriber = "0.2.15"
more-asserts = "0.2.1"
lazy_static = "1.4.0"
path_abs = "0.5.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_info"] }
slog-stdlog = "4.1.0"
