[package]
name = "unftp-sbe-gcs"
version = "0.1.0"
authors = [
    "Agoston Horvath <ahorvath@bol.com>",
    "Dávid Kosztka <dkosztka@bol.com>",
    "Hannes de Jager <hdejager@bol.com>",
    "Rob klein Gunnewiek <rkleingunnewiek@bol.com>",
]
edition = "2018"
license = "Apache-2.0"
keywords = ["libunftp", "unftp", "ftp", "ftps", "storage", "gcs"]
categories = ["network-programming"]
documentation = "https://docs.rs/unftp-sbe-gcs"
homepage = "https://github.com/bolcom/libunftp/tree/master/crates/unftp-sbe-gcs"
repository = "https://github.com/bolcom/libunftp/tree/master/crates/unftp-sbe-gcs"
readme = "README.md"

[dependencies]
async-trait = "0.1.42"
bytes = "1.0.1"
chrono = {version = "0.4.19", features = ["serde"]}
futures = {version = "0.3.12", features = ["std"]}
hyper = { version = "0.14.4", features= ["client", "runtime", "stream", "http1"]}
hyper-rustls = { version = "0.22.1"}
libunftp = { version="0.16.2", path="../../"}
mime = {version = "0.3.16"}
percent-encoding = { version = "2.1.0"}
serde = { version = "1.0.123", features = ["derive"] }
serde_json = { version = "1.0.62"}
tokio = { version = "1.2.0", features = ["rt", "net", "sync", "io-util", "macros", "time", "fs"]}
tokio-stream = "0.1.3"
tokio-util = { version = "0.6.3", features=["codec", "compat"] }
tracing = "0.1.23"
tracing-attributes = "0.1.12"
tracing-futures = { version = "0.2.4", features = ["std", "std-future", "futures-03"]}
yup-oauth2 = {version = "5.0.3"}

[dev-dependencies]
async_ftp = "5.0.0"
clap = "2.33.3"
slog-term = "2.8.0"
slog-async = "2.6.0"
pretty_assertions = "0.6.1"
pretty_env_logger = "0.4.0"
tempfile = "3.2.0"
tokio = { version = "1.2.0", features = ["rt-multi-thread"]}
tracing-subscriber = "0.2.15"
more-asserts = "0.2.1"
lazy_static = "1.4.0"
path_abs = "0.5.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_info"] }
slog-stdlog = "4.1.0"
