[package]
name = "unftp-sbe-gcs"
description = "A storage back-end for libunftp, storing files in Google Cloud Storage (GCS)"
version = "0.1.1"
authors = [
    "Agoston Horvath <ahorvath@bol.com>",
    "Dávid Kosztka <dkosztka@bol.com>",
    "Hannes de Jager <hdejager@bol.com>",
    "Rob klein Gunnewiek <rkleingunnewiek@bol.com>",
]
edition = "2018"
license = "Apache-2.0"
keywords = ["libunftp", "unftp", "ftp", "ftps", "gcs"]
categories = ["network-programming"]
documentation = "https://docs.rs/unftp-sbe-gcs"
homepage = "https://github.com/bolcom/libunftp/tree/master/crates/unftp-sbe-gcs"
repository = "https://github.com/bolcom/libunftp/tree/master/crates/unftp-sbe-gcs"
readme = "README.md"

[dependencies]
async-trait = "0.1.50"
base64 = "0.13.0"
bytes = "1.0.1"
chrono = { version = "0.4.19", default-features = false, features = ["std"] }
futures = {version = "0.3.14", features = ["std"]}
hyper = { version = "0.14.7", features= ["client", "runtime", "stream", "http1"]}
hyper-rustls = { version = "0.22.1"}
libunftp = { version="0.17.4", path="../../"}
mime = {version = "0.3.16"}
percent-encoding = { version = "2.1.0"}
serde = { version = "1.0.125", features = ["derive"] }
serde_json = { version = "1.0.64"}
tokio = { version = "1.5.0", features = ["rt", "net", "sync", "io-util", "time", "fs"] }
tokio-stream = "0.1.5"
tokio-util = { version = "0.6.6", features=["codec", "compat"] }
tracing = { version = "0.1.26", default-features = false }
tracing-attributes = "0.1.15"
yup-oauth2 = {version = "5.0.3"}

[dev-dependencies]
async_ftp = "5.0.0"
clap = "2.33.3"
lazy_static = "1.4.0"
more-asserts = "0.2.1"
path_abs = "0.5.0"
pretty_assertions = "0.7.1"
pretty_env_logger = "0.4.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_info"] }
slog-async = "2.6.0"
slog-stdlog = "4.1.0"
slog-term = "2.8.0"
tempfile = "3.2.0"
tokio = { version = "1.5.0", features = ["macros", "rt-multi-thread"]}
tracing-subscriber = "0.2.15"
