name: Rust build on macos

on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }} with ${{matrix.toolchain}} toolchain
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        toolchain: [stable, beta]

    steps:
    - uses: actions/checkout@v1
    - name: Install rustup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    - name: Switch toolchain
      run: rustup default ${{matrix.toolchain}}
    - name: Add rustfmt and clippy
      run: rustup component add rustfmt clippy
    - name: Rustfmt
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all-features -- -D warnings
    - name: Build
      run: cargo build --verbose --all --all-features
    - name: Run tests
      run: cargo test --verbose --all --all-features
